# Numpy Basics

In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

In [3]:
a_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
type(a_list)

list

In [5]:
a_arr = np.array(a_list)
a_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
type(a_arr)

numpy.ndarray

In [7]:
len(a_list)

10

In [8]:
a_arr.shape

(10,)

In [9]:
a_arr[3]

4

In [10]:
a_arr[2:8]

array([3, 4, 5, 6, 7, 8])

In [11]:
a_arr[2:8:2]

array([3, 5, 7])

In [12]:
a_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
a_arr.reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
a_arr.reshape(5, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [15]:
a_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
a_arr = a_arr.reshape(5, 2)
a_arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [17]:
a_arr.T # Transposing the matrix

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [18]:
a_arr.T.T

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [19]:
list(range(0, 100, 5))

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

In [20]:
# Numpy way of generating serial numbers, similar to range in python
np.arange(0, 100, 5) # Start, Stop, Step

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [21]:
np.arange(0, 15.553, 2.2)

array([ 0. ,  2.2,  4.4,  6.6,  8.8, 11. , 13.2, 15.4])

In [22]:
a_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [23]:
# Python way for element wise addition
[x+5 for x in a_list] 

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [24]:
[x*5 for x in a_list] 

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

In [25]:
a_arr = np.arange(1, 11)
a_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# Numpy way for element wise addision
a_arr + 5 

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
a_arr * 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [28]:
a_arr / 465

array([0.00215054, 0.00430108, 0.00645161, 0.00860215, 0.01075269,
       0.01290323, 0.01505376, 0.0172043 , 0.01935484, 0.02150538])

In [29]:
a = np.arange(100, 300, 2) # Start, Stop, Step
a

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
       152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
       178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202,
       204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228,
       230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254,
       256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280,
       282, 284, 286, 288, 290, 292, 294, 296, 298])

In [30]:
a.shape

(100,)

In [31]:
a = a.reshape(10, 10)
a

array([[100, 102, 104, 106, 108, 110, 112, 114, 116, 118],
       [120, 122, 124, 126, 128, 130, 132, 134, 136, 138],
       [140, 142, 144, 146, 148, 150, 152, 154, 156, 158],
       [160, 162, 164, 166, 168, 170, 172, 174, 176, 178],
       [180, 182, 184, 186, 188, 190, 192, 194, 196, 198],
       [200, 202, 204, 206, 208, 210, 212, 214, 216, 218],
       [220, 222, 224, 226, 228, 230, 232, 234, 236, 238],
       [240, 242, 244, 246, 248, 250, 252, 254, 256, 258],
       [260, 262, 264, 266, 268, 270, 272, 274, 276, 278],
       [280, 282, 284, 286, 288, 290, 292, 294, 296, 298]])

In [32]:
a.mean()

199.0

In [33]:
a.min()

100

In [34]:
a.max()

298

In [35]:
a.std()

57.73214009544424

In [36]:
# Row wise mean
a.mean(axis=1)

array([109., 129., 149., 169., 189., 209., 229., 249., 269., 289.])

In [37]:
# Column Wise mean
a.mean(axis=0)

array([190., 192., 194., 196., 198., 200., 202., 204., 206., 208.])

In [38]:
a.std(axis=1)

array([5.74456265, 5.74456265, 5.74456265, 5.74456265, 5.74456265,
       5.74456265, 5.74456265, 5.74456265, 5.74456265, 5.74456265])

In [39]:
a.std(axis=0)


array([57.44562647, 57.44562647, 57.44562647, 57.44562647, 57.44562647,
       57.44562647, 57.44562647, 57.44562647, 57.44562647, 57.44562647])

In [40]:
np.linspace(1, 10, 15) # start, stop, size

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [41]:
np.arange(1, 10, 0.64285714)

array([1.        , 1.64285714, 2.28571428, 2.92857142, 3.57142856,
       4.2142857 , 4.85714284, 5.49999998, 6.14285712, 6.78571426,
       7.4285714 , 8.07142854, 8.71428568, 9.35714282, 9.99999996])

In [42]:
one = np.ones(100)
one.reshape(10, 10)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [43]:
zero = np.zeros(100)
zero.reshape(10, 10)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [44]:
[[55] * 10] * 10

[[55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
 [55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
 [55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
 [55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
 [55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
 [55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
 [55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
 [55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
 [55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
 [55, 55, 55, 55, 55, 55, 55, 55, 55, 55]]

In [45]:
one.reshape(10, 10) * -55

array([[-55., -55., -55., -55., -55., -55., -55., -55., -55., -55.],
       [-55., -55., -55., -55., -55., -55., -55., -55., -55., -55.],
       [-55., -55., -55., -55., -55., -55., -55., -55., -55., -55.],
       [-55., -55., -55., -55., -55., -55., -55., -55., -55., -55.],
       [-55., -55., -55., -55., -55., -55., -55., -55., -55., -55.],
       [-55., -55., -55., -55., -55., -55., -55., -55., -55., -55.],
       [-55., -55., -55., -55., -55., -55., -55., -55., -55., -55.],
       [-55., -55., -55., -55., -55., -55., -55., -55., -55., -55.],
       [-55., -55., -55., -55., -55., -55., -55., -55., -55., -55.],
       [-55., -55., -55., -55., -55., -55., -55., -55., -55., -55.]])

In [46]:
zero.reshape(10, 10) + -55


array([[-55., -55., -55., -55., -55., -55., -55., -55., -55., -55.],
       [-55., -55., -55., -55., -55., -55., -55., -55., -55., -55.],
       [-55., -55., -55., -55., -55., -55., -55., -55., -55., -55.],
       [-55., -55., -55., -55., -55., -55., -55., -55., -55., -55.],
       [-55., -55., -55., -55., -55., -55., -55., -55., -55., -55.],
       [-55., -55., -55., -55., -55., -55., -55., -55., -55., -55.],
       [-55., -55., -55., -55., -55., -55., -55., -55., -55., -55.],
       [-55., -55., -55., -55., -55., -55., -55., -55., -55., -55.],
       [-55., -55., -55., -55., -55., -55., -55., -55., -55., -55.],
       [-55., -55., -55., -55., -55., -55., -55., -55., -55., -55.]])

In [47]:
np.full((10, 10), 55,)

array([[55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55, 55, 55, 55, 55]])

In [48]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
np.eye(5, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
np.eye(2, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [51]:
np.identity(5, dtype=int) * 18

array([[18,  0,  0,  0,  0],
       [ 0, 18,  0,  0,  0],
       [ 0,  0, 18,  0,  0],
       [ 0,  0,  0, 18,  0],
       [ 0,  0,  0,  0, 18]])

In [52]:
arr = np.arange(1, 13).reshape(3, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
arr2 = np.arange(11, 23).reshape(3, 4)
arr2

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [54]:
arr + arr2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [55]:
arr * arr2 # Element wise multiplication

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171, 200, 231, 264]])

In [56]:
np.dot(arr, arr2.T) # Matrix Multiplication

array([[130, 170, 210],
       [330, 434, 538],
       [530, 698, 866]])

In [57]:
np.dot(arr.T, arr2) # Matrix Multiplication


array([[257, 272, 287, 302],
       [302, 320, 338, 356],
       [347, 368, 389, 410],
       [392, 416, 440, 464]])

In [58]:
arr.dot(arr2.T)

array([[130, 170, 210],
       [330, 434, 538],
       [530, 698, 866]])

In [59]:
arr2.dot(arr.T)

array([[130, 330, 530],
       [170, 434, 698],
       [210, 538, 866]])

In [60]:
mat = np.dot(arr.T, arr2)
mat

array([[257, 272, 287, 302],
       [302, 320, 338, 356],
       [347, 368, 389, 410],
       [392, 416, 440, 464]])

In [61]:
np.linalg.inv(mat) # Inverse of a matrix

array([[ 1.75921860e+13, -1.75921860e+13, -1.75921860e+13,
         1.75921860e+13],
       [-2.34562481e+13,  1.75921860e+13,  3.51843721e+13,
        -2.93203101e+13],
       [-5.86406201e+12,  1.75921860e+13, -1.75921860e+13,
         5.86406201e+12],
       [ 1.17281240e+13, -1.75921860e+13, -0.00000000e+00,
         5.86406201e+12]])

In [62]:
mat

array([[257, 272, 287, 302],
       [302, 320, 338, 356],
       [347, 368, 389, 410],
       [392, 416, 440, 464]])

In [63]:
mat.flatten()

array([257, 272, 287, 302, 302, 320, 338, 356, 347, 368, 389, 410, 392,
       416, 440, 464])

In [64]:
mat.ravel()

array([257, 272, 287, 302, 302, 320, 338, 356, 347, 368, 389, 410, 392,
       416, 440, 464])

In [65]:
import time

In [66]:
now = time.process_time()
list(range(10_00_00_000))
print(f'Time Taken: {time.process_time() - now}')

Time Taken: 1.203125


In [67]:
now = time.process_time()
np.arange(10_00_00_000)
print(f'Time Taken: {time.process_time() - now}')

Time Taken: 0.078125


In [69]:
1.203125 / 0.078125

15.4